### ISSUE TITLE
Series of issues in running org.aksw.rex.controller.RexController

### ISSUE THREAD

**Issue by kannangce** [dice-group/REX#2]
I am playing around with REX, I see a series of issue in following [this instruction](https://github.com/dice-group/REX/wiki/4---Run).

- I got the below error,
>org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:cache/sparql/sparql-cache;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-181]

  To fix the above issue, I had to add the prefix `./` for the values of member variables `org.aksw.rex.examplegenerator.SimpleExampleGenerator.cacheDirectory` and `org.aksw.rex.consistency.ConsistencyCheckerImpl.cacheDirectory`.

- After fixing the above, getting the below exception,

> Exception in thread "main" java.lang.RuntimeException: Deprecated; do not use
> 	at org.aksw.jena_sparql_api.cache.h2.CacheCoreH2._lookup(CacheCoreH2.java:235)
> 	at org.aksw.jena_sparql_api.cache.h2.CacheCoreH2.lookup(CacheCoreH2.java:205)
> 	at org.aksw.jena_sparql_api.cache.extra.CacheCoreExCompressor.lookup(CacheCoreExCompressor.java:56)
> 	at org.aksw.jena_sparql_api.cache.extra.CacheFrontendImpl.lookup(CacheFrontendImpl.java:96)
> 	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:97)
> 	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.execSelect(QueryExecutionCacheEx.java:204)
> 	at org.aksw.rex.examplegenerator.SimpleExampleGenerator.executeSelectQuery(SimpleExampleGenerator.java:421)
> 	at org.aksw.rex.examplegenerator.SimpleExampleGenerator.getMostProminentPositiveExamples(SimpleExampleGenerator.java:149)
> 	at org.aksw.rex.examplegenerator.SimpleExampleGenerator.getPositiveExamples(SimpleExampleGenerator.java:98)
> 	at org.aksw.rex.controller.RexController.run(RexController.java:144)
> 	at org.aksw.rex.controller.RexController.main(RexController.java:112)

It turns out to be that the class used by the existing code is deprecated. So made [this fix](https://github.com/kannangce/REX/commit/6d627f11caf6ff65c71bb75214337ebc6982ed0c) to get beyond this issue.

- Once the above issue is fixed, getting the below exception,
> Virtuoso 42000 Error The estimated execution time 278 (sec) exceeds the limit of 240 (sec).
To get around that error setup a [Virtuoso server](https://github.com/tenforce/docker-virtuoso) in my local and trying.

The current challenge is my local SPARQL not having the pre-loaded data that is already available in DBPedia. Trying out a way to load my SPARQL with the necessary data.

Keep fiddling around it. Any help would be greatly helpful.

**Comment by RicardoUsbeck** [comment]
Maybe you can try a newer version of the jena_sparql_api from here https://github.com/SmartDataAnalytics/jena-sparql-api 

Unfortunately, we didn't keep up with maintaining the project.
